import { Rubik } from "next/font/google";
import "./globals.css";
import { NoteProvider } from "../context/noteContext";

//components
import Navbar from './components/Navbar'

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Note Manager App",
  description: "Generated by Hussein Daher",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar />
        <NoteProvider>
          {children}
        </NoteProvider>
      </body>
    </html>
  );
}
